# 端口
server:
    port: 9000

# Sa-Token 配置
sa-token:
    # -------------- SSO-模式一相关配置  (非模式一不需要配置)
    # cookie:
         # 配置Cookie作用域
         # domain: stp.com

    # ------- SSO-模式二相关配置
    sso:
        # Ticket有效期 (单位: 秒)，默认五分钟
        ticket-timeout: 300
        # 所有允许的授权回调地址
        allow-url: "*"
        # 是否打开单点注销功能
        is-slo: true

        # ------- SSO-模式三相关配置 （下面的配置在SSO模式三并且 is-slo=true 时打开） -------
        # 是否打开模式三
        isHttp: true
        # 接口调用秘钥（用于SSO模式三的单点注销功能）
        secretkey: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
        # ---- 除了以上配置项，你还需要为 Sa-Token 配置http请求处理器（文档有步骤说明）
spring:
    #环境变量
    profiles:
      active: datasource
# MyBatis
mybatis:
# 搜索指定包别名
  type-aliases-package: com.dongao.system
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  config-location: classpath:mapper/mybatis-config.xml




